### ISSUE TITLE
Is it possible to use this with systemd as there are no pid files?

### ISSUE THREAD

**Issue by uumas** [Sorunome/matrix-synchrotron-balancer#5]
Using the systemd setup documented at https://github.com/matrix-org/synapse/tree/master/docs/systemd-with-workers

**Comment by Sorunome** [comment]
you could either use synctl in your unit files or modify your unit files to create a PID file, with something like
```
python start-worker-stuff &
echo $! > /run/syncrotron.pid
```

see https://superuser.com/questions/238412/write-a-pid-file-manually-from-bash-script

**Comment by cremesk** [comment]
found a workaround for systemd:

```
ExecStartPost=/bin/sh -c 'umask 022; pgrep -f "/opt/venvs/matrix-synapse/bin/python -m synapse.app.generic_worker --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --config-path=/etc/matrix-synapse/workers/%i" | head -1 > /etc/matrix-synapse/workers/%i.pid'
```

add this after `ExecStart=` in the [matrix-synapse-worker@.service](https://github.com/matrix-org/synapse/blob/develop/docs/systemd-with-workers/system/matrix-synapse-worker%40.service#L19).

Now you can use the pid file in your synchrotron config.yaml.
for example:
```
..
synchrotrons:
  - address: localhost:8510
    pid_file: /etc/matrix-synapse/workers/generic_worker1.pid
  - address: localhost:8511
    pid_file: /etc/matrix-synapse/workers/generic_worker2.pid
..
```
